// ============================================================
// ROLLING PLAN — Phase 1 architectural guards.
//
// The plan is a rolling, continuous forecast; `weeksShown` is a DISPLAY
// horizon only. Changing it must not change the underlying training logic.
// There is no block boundary — the last visible week is an ordinary week,
// never a taper/handoff/reset. The engine can generate arbitrarily many
// weeks beyond the visible window.
// ============================================================

import { describe, it, expect } from 'vitest';
import { resolveEffectivePlan } from '../planOverlay';
import { defaultSettings, buildWeekConfigsFromSettings, clampWeeksShown } from '../settings';
import type { RawSettings, RunState } from '../types';

const NOW = '2026-07-08T12:00:00Z';
const TODAY = '2026-07-08';

function raw(patch: Partial<RawSettings> = {}): RawSettings {
  return { ...defaultSettings(NOW), ...patch };
}
function scenarioLog(): RunState {
  return {
    '2026-06-29': { date: '2026-06-29', done: true, miles_actual: 4.2, updated_at: NOW },
    '2026-06-30': { date: '2026-06-30', done: true, miles_actual: 4.0, updated_at: NOW },
    '2026-07-01': { date: '2026-07-01', done: true, miles_actual: 4.0, updated_at: NOW },
    '2026-07-02': { date: '2026-07-02', done: true, miles_actual: 3.5, updated_at: NOW },
    '2026-07-03': { date: '2026-07-03', done: true, miles_actual: 4.5, updated_at: NOW },
    '2026-07-06': { date: '2026-07-06', done: true, miles_actual: 4.5, updated_at: NOW },
  };
}
function scenarioSettings(patch: Partial<RawSettings> = {}): RawSettings {
  return raw({ startMpw: 20, peakMpw: 30, buildStep: 1, downEvery: 4, weeksShown: 7, trailingLongest: 4.5, ...patch });
}

describe('weeksShown is a display horizon, NOT a training boundary', () => {
  it('the first N weeks of a longer window are BYTE-IDENTICAL to a shorter window of length N', () => {
    // Weeks are generated by an ordinal-i-based engine that never looks at
    // weeksShown to compute values (it only decides when to stop). So a 20-
    // week plan's first 7 weeks equal a 7-week plan verbatim, and its first
    // 12 weeks equal a 12-week plan.
    const N = [4, 7, 12, 20];
    const plans = N.map(n => resolveEffectivePlan(scenarioSettings({ weeksShown: n }), scenarioLog(), TODAY).plan.weeks);
    for (let i = 1; i < plans.length; i++) {
      const prev = plans[i - 1];
      const cur = plans[i].slice(0, prev.length);
      expect(cur.length).toBe(prev.length);
      for (let j = 0; j < prev.length; j++) {
        expect(cur[j].totalPlanned).toBeCloseTo(prev[j].totalPlanned, 5);
        expect(cur[j].longRunCap).toBeCloseTo(prev[j].longRunCap, 5);
        expect(cur[j].isDownWeek).toBe(prev[j].isDownWeek);
        expect(cur[j].note).toBe(prev[j].note);
      }
    }
  });

  it('the engine can extend arbitrarily far beyond weeksShown', () => {
    // Passing an explicit count > weeksShown produces that many weeks —
    // proving the plan is rolling, not block-bounded.
    const short = resolveEffectivePlan(scenarioSettings({ weeksShown: 4 }), scenarioLog(), TODAY, { count: 4 }).plan.weeks;
    const long = resolveEffectivePlan(scenarioSettings({ weeksShown: 4 }), scenarioLog(), TODAY, { count: 20 }).plan.weeks;
    expect(short.length).toBe(4);
    expect(long.length).toBe(20);
    // And the first 4 weeks are identical.
    for (let j = 0; j < 4; j++) expect(long[j].totalPlanned).toBeCloseTo(short[j].totalPlanned, 5);
  });

  it('buildWeekConfigsFromSettings accepts an explicit count that overrides weeksShown', () => {
    const cfgs = buildWeekConfigsFromSettings(raw({ startMpw: 20, peakMpw: 30, buildStep: 2, weeksShown: 5 }), 20);
    expect(cfgs.length).toBe(20);
  });

  it('clampWeeksShown accepts 4–24 (a display window, not a training constant)', () => {
    expect(clampWeeksShown(0)).toBe(1);
    expect(clampWeeksShown(100)).toBe(24);
    expect(clampWeeksShown(7)).toBe(7);
  });
});

describe('the last visible week has no special-case treatment', () => {
  it('no rolling week ever carries a stale block-boundary note (handoff / taper)', () => {
    for (const n of [4, 7, 12, 20]) {
      const weeks = resolveEffectivePlan(scenarioSettings({ weeksShown: n }), scenarioLog(), TODAY).plan.weeks;
      for (const w of weeks) {
        expect(w.note).not.toBe('handoff');
        expect(w.note).not.toBe('taper');
      }
    }
  });

  it('the last visible week is NOT forced to be non-down — cadence continues rolling', () => {
    // With downEvery=3 and enough weeks, some window sizes will legitimately
    // end on a down week (that's a display boundary, not a training reset).
    const cfgs = buildWeekConfigsFromSettings(raw({ startMpw: 20, peakMpw: 30, buildStep: 2, downEvery: 3, weeksShown: 20 }));
    const anyEndsOnDown = [3, 6, 9, 12, 15, 18].some(len => cfgs[len - 1]?.isDownWeek);
    expect(anyEndsOnDown).toBe(true);
  });
});

describe('rolling progression preserves the previous progression fix', () => {
  it('completed weeks stay locked (locked prescription is byte-identical across settings changes)', () => {
    const a = resolveEffectivePlan(scenarioSettings({ peakMpw: 30 }), scenarioLog(), TODAY).plan.weeks;
    const b = resolveEffectivePlan(scenarioSettings({ peakMpw: 45 }), scenarioLog(), TODAY).plan.weeks;
    expect(a.slice(0, 2).map(w => w.totalPlanned)).toEqual(b.slice(0, 2).map(w => w.totalPlanned));
  });

  it('logged runs are never mutated by resolving the plan (rolling or otherwise)', () => {
    const log = scenarioLog();
    const before = JSON.stringify(log);
    resolveEffectivePlan(scenarioSettings({ weeksShown: 20 }), log, TODAY);
    resolveEffectivePlan(scenarioSettings({ weeksShown: 4 }), log, TODAY, { count: 30 });
    expect(JSON.stringify(log)).toBe(before);
  });

  it('safe total / season goal do NOT cap future weekly targets (still display-only)', () => {
    const generous = resolveEffectivePlan(scenarioSettings({ goalMiles: 300, safeDelivery: 300 }), scenarioLog(), TODAY).plan.weeks;
    const stingy = resolveEffectivePlan(scenarioSettings({ goalMiles: 100, safeDelivery: 60 }), scenarioLog(), TODAY).plan.weeks;
    expect(stingy.map(w => w.totalPlanned)).toEqual(generous.map(w => w.totalPlanned));
  });

  it('the week AFTER a down week resumes the BUILD trajectory (not the dip)', () => {
    const weeks = resolveEffectivePlan(scenarioSettings({ weeksShown: 20 }), scenarioLog(), TODAY).plan.weeks;
    for (let i = 1; i < weeks.length - 1; i++) {
      if (!weeks[i].isDownWeek) continue;
      const before = weeks[i - 1].totalPlanned;
      const after = weeks[i + 1].totalPlanned;
      // The week after the down is at least the down week; if we're not yet at
      // peak, it should also be at or above the pre-down trajectory.
      expect(after).toBeGreaterThan(weeks[i].totalPlanned - 1e-9);
      expect(after).toBeGreaterThanOrEqual(before - 1.5); // splitWeek round-loss headroom
    }
  });
});
